#ASSIGNMENT=wp1p1
#ASSIGNMENT=wp1
#ASSIGNMENT=wp2
#ASSIGNMENT=wp3
ASSIGNMENT=project
TEAM_MEMBERS_CSV="mingchen zhang sbuid: 110138345 shengchun liu sbid:110151878"
# list space-separated completed components: cooperative preemptive signals swap filesystem network multicore
PROJECT_PARTS=cooperative preemptive signals filesystem
PROJECT_POINTS=80

# Submission Note:
# launch the OS with: qemu-system-x86_64 -curses -drive id=boot,format=raw,file=shengliu.img,if=none -drive id=data,format=raw,file=shengliu-data.img,if=none -device ahci,id=ahci -device ide-drive,drive=boot,bus=ahci.0 -device ide-drive,drive=data,bus=ahci.1 -gdb tcp::9999
# PROJECT_PARTS=cooperative preemptive signals filesystem
# Preemptive multi-tasking is enabled by default
# SIGINT SIGKILL SIGSEGV SIGALRM is defined. for other signal, please use number directly instead.
# All Functional Requirements is met
# ctr+c is supported to send SIGINT to forground process 
# kill binary send SIGKILL by default, a number could be given as the second parameter to specify the signal number to send
# to test kill, a background process could be launched by appending & after the command in sbush
# ps will list all process id and their executable path, this also includes zombie processes
# No file redirection is implemented in sbush (like wq1). 
# Disk File system:
#	On disk file system is implemented. Disk file system is automatically formated upon boot. 
#	/bin/disk_test binary is used to test read and write. 
#	file listing is also supported for disk file, but listing file in a directory that exist on both tarfs and disk filesystem only reveal tarfs files. 
#	directory is automatically created when a file is created by open syscall with O_CREAT flag.
#	only O_WRONLY and O_RDONLY is supported, O_RDWR is not supported. 
#	(If a bug appears during disk operation, please try again)
# Note regarding 106 physical machine:
#	Due to a bootloader bug, when the image is larger than a certain size, the bootloader would fail on 106 machine.
#	There are suggestion on piazza regarding circumventing this problem by removing some libc files, but the final project needs these lib to properly work.
#	Since no proper solution to this bootloader problem was posted, and I can't solve this myself. The Os would fail to boot on 106 machine. 